<a href="https://colab.research.google.com/github/tusharmaaa/creditcardfrauddetection/blob/main/credit_card_fraud_detection_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
Dataset=pd.read_csv("/content/credit_card_fraud.csv")
Dataset

Transaction Date and Time  Transaction Amount        Cardholder Name  \
0          2022-09-24 13:54:27              285.88            Shray Soman   
1          2020-07-24 11:20:13             1777.32         Lakshit Bakshi   
2          2023-03-18 01:05:36             3939.01             Riya Bobal   
3          2021-01-07 21:53:04              376.44  Mohanlal Balakrishnan   
4          2021-12-16 06:22:24             1687.33            Mannat Rout   
...                        ...                 ...                    ...   
7995       2020-12-17 20:36:48             2214.15         Lakshay Khatri   
7996       2022-07-04 05:19:11              675.97        Dharmajan Salvi   
7997       2022-08-14 19:14:45              918.28              Alia Sane   
7998       2021-05-16 18:21:52             3035.31            Chirag Rege   
7999       2023-06-14 06:12:26             3354.36              Alia Bose   

                      Card Number (Hashed or Encrypted)  \
0     daca51bffe0fc4eaaa7c430917f94b75fd893712492254...   
1     d5366dd9be3a0266c0252baceaa6332210ed4dbd0ef252...   
2     4737a6384aa1c3c31f7768b86633d6a8401dd6ab4a8ff1...   
3     4721806eed8f2663bb597ff13e79a294de318358fbb54b...   
4     9deacc3a9efd6e382826d400620aca5f23ed94327578e5...   
...                                                 ...   
7995  8a0015c8601fe597e160c31a05fd5e4a87a4b876df426f...   
7996  de3530e65ccf6fc0c0eb7f7a7e8e5b71bb907d5207d390...   
7997  227356d19fd5374e9cfdd134387fe3499683a1c7929981...   
7998  669bd9fcc7e40cc25d99c773678e48bcb3fdadf7fee6a9...   
7999  8db138a97db4df2c7533dfca014dcd85c0385846a55e6c...   

                    Merchant Name  Merchant Category Code (MCC)  \
0     Rajagopalan, Ghose and Kant                          3590   
1                        Sule PLC                          7277   
2                       Badal PLC                          9297   
3                     Konda-Sodhi                          5686   
4                         Dua Ltd                          2940   
...                           ...                           ...   
7995                    Manda Ltd                          1236   
7996                Bhavsar Group                          3406   
7997   Gole, Yohannan and Singhal                          7504   
7998                    Kakar LLC                          4015   
7999        Datta, Gandhi and Sha                          2902   

     Transaction Location (City or ZIP Code) Transaction Currency  \
0                                    Khammam                  INR   
1                                Vasai-Virar                  EUR   
2                                Nangloi Jat                  USD   
3                                 Ramagundam                  USD   
4                                      Adoni                  INR   
...                                      ...                  ...   
7995                             Anantapuram                  EUR   
7996                                Guntakal                  INR   
7997                                   Udupi                  USD   
7998                        Sultan Pur Majra                  EUR   
7999                                Dehradun                  INR   

             Card Type Card Expiration Date  \
0           MasterCard                04/29   
1     American Express                03/26   
2                 Visa                11/29   
3                 Visa                09/25   
4           MasterCard                03/31   
...                ...                  ...   
7995              Visa                04/26   
7996              Visa                11/25   
7997        MasterCard                05/24   
7998  American Express                09/24   
7999              Visa                02/24   

                         CVV Code (Hashed or Encrypted)  \
0     01299ac65733b5a3d774265fbfe8396b8611e5e3321855...   
1     ad8fa913d25b3970c6efa8ca504da8ba670ce2a9cf012d..

In [ ]:
# Replace "none" with 0 and "3 or more" with 3 in the "Previous Transactions" column
Dataset['Previous Transactions'] = Dataset['Previous Transactions'].replace({'None': '0', '3 or more': '3'})

# Check the unique values in the "Previous Transactions" column after replacement
print(Dataset['Previous Transactions'].unique())

['0' '3' '2' '1']


In [ ]:
# Frequency Encoding for Transaction Location
location_counts = Dataset['Transaction Location (City or ZIP Code)'].value_counts()
Dataset['Location Frequency'] = Dataset['Transaction Location (City or ZIP Code)'].map(location_counts)

# Target Encoding for Transaction Location
location_means = Dataset.groupby('Transaction Location (City or ZIP Code)')['Fraud Flag or Label'].mean()
Dataset['Location Target Encoding'] = Dataset['Transaction Location (City or ZIP Code)'].map(location_means)


In [ ]:
new_column_name = "card_expiration_date"  # New name for the column
df_processed= Dataset.rename(columns={"Card Expiration Date": new_column_name })
df_processed.card_expiration_date = pd.to_datetime(df_processed.card_expiration_date, format="%m/%y")

In [ ]:
# Frequency encoding for Cardholder Name
cardholder_counts = df_processed['Cardholder Name'].value_counts()
df_processed['Cardholder Frequency'] = df_processed['Cardholder Name'].map(cardholder_counts)

# Target encoding for Merchant Name
merchant_means = df_processed.groupby('Merchant Name')['Fraud Flag or Label'].mean()
df_processed['Merchant Target Encoding'] = df_processed['Merchant Name'].map(merchant_means)

In [ ]:
df_processed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 24 columns):
 #   Column                                   Non-Null Count  Dtype         
---  ------                                   --------------  -----         
 0   Transaction Date and Time                8000 non-null   object        
 1   Transaction Amount                       8000 non-null   float64       
 2   Cardholder Name                          8000 non-null   object        
 3   Card Number (Hashed or Encrypted)        8000 non-null   object        
 4   Merchant Name                            8000 non-null   object        
 5   Merchant Category Code (MCC)             8000 non-null   int64         
 6   Transaction Location (City or ZIP Code)  8000 non-null   object        
 7   Transaction Currency                     8000 non-null   object        
 8   Card Type                                8000 non-null   object        
 9   card_expiration_date                     

In [ ]:
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder

# Standardize Transaction Amount
scaler = StandardScaler()
df_processed['Standardized Amount'] = scaler.fit_transform(df_processed[['Transaction Amount']])

# Encode Card Type using Label Encoding
label_encoder = LabelEncoder()
df_processed['Card Type Numerical'] = label_encoder.fit_transform(df_processed['Card Type'])

# Encode Card Type using One-Hot Encoding (if needed)
#one_hot_encoder = OneHotEncoder()
#card_type_encoded = one_hot_encoder.fit_transform(df_processed[['Card Type']]).toarray()
#df_processed = pd.concat([df_processed, pd.DataFrame(card_type_encoded, columns=one_hot_encoder.get_feature_names_out(['Card Type']))], axis=1)

# Define feature columns and target variable
feature_columns = ['Location Frequency', 'Location Target Encoding', 'Merchant Target Encoding', 'Standardized Amount', 'Card Type Numerical','Previous Transactions']
target_column = 'Fraud Flag or Label'

# Prepare X (features) and y (target)
X = df_processed[feature_columns]
y = df_processed[target_column]


In [ ]:
# Print the number of columns and their names in X (features)
print("Number of columns in X:", X.shape[1])
print("Column names in X:")
print(X.columns.tolist())

# Print the number of columns and their names in y (target variable)
print("\nNumber of columns in y:", 1)  # Since y is a single column (target variable)
print("Column name in y:", y.name)


Number of columns in X: 6
Column names in X:
['Location Frequency', 'Location Target Encoding', 'Merchant Target Encoding', 'Standardized Amount', 'Card Type Numerical', 'Previous Transactions']

Number of columns in y: 1
Column name in y: Fraud Flag or Label


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize RandomForestClassifier
clf = RandomForestClassifier(random_state=42)

# Train the model
clf.fit(X_train, y_train)

# Predict on the testing set
y_pred = clf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Generate classification report
conf_matrix = confusion_matrix(y_test, y_pred)

print("\nConfusion Matrix:")
print(conf_matrix)
report = classification_report(y_test, y_pred)
print("Classification Report:\n", report)


Accuracy: 0.939375

Confusion Matrix:
[[742  51]
 [ 46 761]]
Classification Report:
               precision    recall  f1-score   support

           0       0.94      0.94      0.94       793
           1       0.94      0.94      0.94       807

    accuracy                           0.94      1600
   macro avg       0.94      0.94      0.94      1600
weighted avg       0.94      0.94      0.94      1600



In [ ]:
from sklearn.naive_bayes import GaussianNB

# Assuming you have already divided your dataset into features (X) and target (y)
# X should contain the features and y should contain the target variable (Fraud Flag or Label)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Naive Bayes classifier
nb_classifier = GaussianNB()

# Train the classifier on the training data
nb_classifier.fit(X_train, y_train)

# Make predictions on the testing data
y_pred = nb_classifier.predict(X_test)

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Compute confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Generate classification report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)


Accuracy: 0.9425
Confusion Matrix:
[[740  53]
 [ 39 768]]
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       793
           1       0.94      0.95      0.94       807

    accuracy                           0.94      1600
   macro avg       0.94      0.94      0.94      1600
weighted avg       0.94      0.94      0.94      1600



In [ ]:
import pandas as pd
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

# Define the classifiers
classifiers = {
    'Random Forest': RandomForestClassifier(),
    'Logistic Regression': LogisticRegression(),
    'Support Vector Machine': SVC(),
    'Naive Bayes': GaussianNB()
}

# Initialize lists to store evaluation metrics
accuracy_scores = []
precision_scores = []
recall_scores = []
f1_scores = []

# Perform cross-validation for each classifier
for name, clf in classifiers.items():
    # Perform cross-validation (5-fold) and compute evaluation metrics
    accuracy = cross_val_score(clf, X, y, cv=5, scoring='accuracy').mean()
    precision = cross_val_score(clf, X, y, cv=5, scoring='precision').mean()
    recall = cross_val_score(clf, X, y, cv=5, scoring='recall').mean()
    f1 = cross_val_score(clf, X, y, cv=5, scoring='f1').mean()

    # Append the evaluation metrics to the lists
    accuracy_scores.append(accuracy)
    precision_scores.append(precision)
    recall_scores.append(recall)
    f1_scores.append(f1)

# Create a DataFrame to store evaluation metrics
results_df = pd.DataFrame({
    'Classifier': classifiers.keys(),
    'Accuracy': accuracy_scores,
    'Precision': precision_scores,
    'Recall': recall_scores,
    'F1 Score': f1_scores
})

# Display the results
print("Evaluation Metrics for Different Classifiers:")
print(results_df)

Evaluation Metrics for Different Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
0           Random Forest  0.943750   0.943366  0.941840  0.941530
1     Logistic Regression  0.947500   0.947443  0.947354  0.947361
2  Support Vector Machine  0.941500   0.948640  0.933572  0.940904
3             Naive Bayes  0.948625   0.947072  0.950365  0.948604


In [ ]:
from sklearn.ensemble import VotingClassifier

# Define the base classifiers
base_classifiers = [
    ('Logistic Regression', LogisticRegression()),
    ('Naive Bayes', GaussianNB())
]

# Create a voting classifier with hard voting
voting_hard = VotingClassifier(estimators=base_classifiers, voting='hard')

# Create a voting classifier with soft voting
voting_soft = VotingClassifier(estimators=base_classifiers, voting='soft')

# Perform cross-validation for the voting classifiers
accuracy_hard = cross_val_score(voting_hard, X, y, cv=5, scoring='accuracy').mean()
accuracy_soft = cross_val_score(voting_soft, X, y, cv=5, scoring='accuracy').mean()

# Print the accuracy of the voting classifiers
print("Accuracy of Hard Voting Classifier:", accuracy_hard)
print("Accuracy of Soft Voting Classifier:", accuracy_soft)


Accuracy of Hard Voting Classifier: 0.947875
Accuracy of Soft Voting Classifier: 0.947625


In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Assuming you have already divided your dataset into features (X) and target (y)
# X should contain the features and y should contain the target variable (Fraud Flag or Label)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train Random Forest classifier (Bagging)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

# Make predictions on the testing data
rf_y_pred = rf_classifier.predict(X_test)

# Calculate accuracy for Random Forest
rf_accuracy = accuracy_score(y_test, rf_y_pred)
print("Random Forest Accuracy:", rf_accuracy)

# Generate confusion matrix for Random Forest
rf_conf_matrix = confusion_matrix(y_test, rf_y_pred)
print("Random Forest Confusion Matrix:")
print(rf_conf_matrix)

# Generate classification report for Random Forest
rf_class_report = classification_report(y_test, rf_y_pred)
print("Random Forest Classification Report:")
print(rf_class_report)

# Initialize and train AdaBoost classifier
adaboost_classifier = AdaBoostClassifier(n_estimators=100, random_state=42)
adaboost_classifier.fit(X_train, y_train)

# Make predictions on the testing data
adaboost_y_pred = adaboost_classifier.predict(X_test)

# Calculate accuracy for AdaBoost
adaboost_accuracy = accuracy_score(y_test, adaboost_y_pred)
print("AdaBoost Accuracy:", adaboost_accuracy)

# Generate confusion matrix for AdaBoost
adaboost_conf_matrix = confusion_matrix(y_test, adaboost_y_pred)
print("AdaBoost Confusion Matrix:")
print(adaboost_conf_matrix)

# Generate classification report for AdaBoost
adaboost_class_report = classification_report(y_test, adaboost_y_pred)
print("AdaBoost Classification Report:")
print(adaboost_class_report)


Random Forest Accuracy: 0.939375
Random Forest Confusion Matrix:
[[742  51]
 [ 46 761]]
Random Forest Classification Report:
              precision    recall  f1-score   support

           0       0.94      0.94      0.94       793
           1       0.94      0.94      0.94       807

    accuracy                           0.94      1600
   macro avg       0.94      0.94      0.94      1600
weighted avg       0.94      0.94      0.94      1600

AdaBoost Accuracy: 0.943125
AdaBoost Confusion Matrix:
[[741  52]
 [ 39 768]]
AdaBoost Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.93      0.94       793
           1       0.94      0.95      0.94       807

    accuracy                           0.94      1600
   macro avg       0.94      0.94      0.94      1600
weighted avg       0.94      0.94      0.94      1600

